# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Loewen & Partners Inc.

description: > # this means to ignore newlines until "baseurl:"
 Passionate About Private Company Investment Banking 
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

John C. Loewen
email: jloewen@loewenpartners.ca
Phone: +1 416 821 5795

plugins:
  - jekyll-seo-tag

# Build settings
markdown: kramdown

gems: ['kramdown','jekyll-seo-tag']
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile']

defaults:
- scope:
    path: _posts
    type: posts
  values:
    layout: post
    sectionid: blog

collections:
  posts:
    permalink: /blog/:year/:month/:day/:title/
    output: true
  proj_files:
    output: false
